# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I, Marslo
email: marslo.jiao@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h2>Hello, there!</h2><h1>Welcome to my world!</h1>"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marslo.github.io" # the base hostname & protocol for your site
twitter_username: marslo
github_username:  marslo

# Build settings
markdown: kramdown
